FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

COPY *.csproj ./
RUN dotnet restore

COPY . .
RUN dotnet ef migrations bundle \
    --self-contained -r linux-x64 \
    --configuration Release \
    -o /app/efbundle

FROM mcr.microsoft.com/dotnet/runtime-deps:10.0
WORKDIR /app
COPY --from=build /app/efbundle .
ENTRYPOINT ["./efbundle"]